name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y spdlog
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Run tests
      run: ./runTests