name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev
        sudo apt-get install -y libcurl4-openssl-dev
        # You might need other dependencies based on your project's requirements.

    - name: Install vcpkg (package manager for C++)
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: Install cpr, nlohmann_json, and spdlog using vcpkg
      run: |
        ./vcpkg/vcpkg install cpr nlohmann-json spdlog

    - name: Create build directory
      run: mkdir build

    - name: Run CMake and build
      run: |
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
        make

    - name: Run tests (if you have any)
      run: ./build/runTests

